var searchData=
[
  ['readme_2emd_91',['README.md',['../README_8md.html',1,'']]],
  ['robot_92',['Robot',['../classsun_1_1Robot.html',1,'sun::Robot'],['../classsun_1_1Robot.html#a4bdfae93e003ae3d5957724d1a7e205d',1,'sun::Robot::Robot()'],['../classsun_1_1Robot.html#a1e96043c0b23fec26fbc907edf4ce2e5',1,'sun::Robot::Robot(const std::string &amp;name)'],['../classsun_1_1Robot.html#afafe4010b453aff93e17282998a952f2',1,'sun::Robot::Robot(const std::vector&lt; RobotLinkPtr &gt; &amp;links, const TooN::Matrix&lt; 4, 4 &gt; &amp;b_T_0, const TooN::Matrix&lt; 4, 4 &gt; &amp;n_T_e, double dls_joint_speed_saturation, const std::string &amp;name)'],['../classsun_1_1Robot.html#a2fcff8a212d062d31b96e5115181d23a',1,'sun::Robot::Robot(const TooN::Matrix&lt; 4, 4 &gt; &amp;b_T_0, const TooN::Matrix&lt; 4, 4 &gt; &amp;n_T_e, double dls_joint_speed_saturation, const std::string &amp;name)'],['../classsun_1_1Robot.html#a1665721dd05638e207dfc0747cd050bc',1,'sun::Robot::Robot(const Robot &amp;robot)']]],
  ['robot_2ecpp_93',['Robot.cpp',['../Robot_8cpp.html',1,'']]],
  ['robot_2eh_94',['Robot.h',['../Robot_8h.html',1,'']]],
  ['robot_5fcreset_95',['ROBOT_CRESET',['../RobotLink_8h.html#afbfb2ec2a9dbe07977d2124d75fbb55f',1,'RobotLink.h']]],
  ['robot_5ferror_5fcolor_96',['ROBOT_ERROR_COLOR',['../RobotLink_8h.html#a493e5cea66877dd966e4bdabd0c87789',1,'RobotLink.h']]],
  ['robot_5fwarning_5fcolor_97',['ROBOT_WARNING_COLOR',['../RobotLink_8h.html#a8d7657745daeffcc6a97b32bdeb64912',1,'RobotLink.h']]],
  ['robotlink_98',['RobotLink',['../classsun_1_1RobotLink.html',1,'sun::RobotLink'],['../classsun_1_1RobotLink.html#a74825b995dd70304f7da63a7b38ad4d3',1,'sun::RobotLink::RobotLink(double a, double alpha, double d, double theta, double robot2dh_offset, bool robot2dh_flip, double Joint_Hard_limit_lower, double Joint_Hard_limit_higher, double Joint_Soft_limit_lower, double Joint_Soft_limit_higher, double hard_velocity_limit, double soft_velocity_limit, std::string name=&quot;joint_no_name&quot;)'],['../classsun_1_1RobotLink.html#ad3b26aac267bb8cd2e2b144b88c98d8b',1,'sun::RobotLink::RobotLink(double a, double alpha, double d, double theta, double robot2dh_offset=0.0, bool robot2dh_flip=false, double Joint_Hard_limit_lower=-INFINITY, double Joint_Hard_limit_higher=INFINITY, double hard_velocity_limit=INFINITY, std::string name=&quot;joint_no_name&quot;)']]],
  ['robotlink_2ecpp_99',['RobotLink.cpp',['../RobotLink_8cpp.html',1,'']]],
  ['robotlink_2eh_100',['RobotLink.h',['../RobotLink_8h.html',1,'']]],
  ['robotlinkprismatic_101',['RobotLinkPrismatic',['../classsun_1_1RobotLinkPrismatic.html',1,'sun::RobotLinkPrismatic'],['../classsun_1_1RobotLinkPrismatic.html#abc202a177a74fe9282230c7cd9bcd993',1,'sun::RobotLinkPrismatic::RobotLinkPrismatic(double a, double alpha, double theta, double robot2dh_offset, bool robot2dh_flip, double Joint_Hard_limit_lower, double Joint_Hard_limit_higher, double Joint_Soft_limit_lower, double Joint_Soft_limit_higher, double hard_velocity_limit, double soft_velocity_limit, std::string name=&quot;joint_no_name&quot;)'],['../classsun_1_1RobotLinkPrismatic.html#aa52dff2de4fc27fddb27d4685c1d2aa0',1,'sun::RobotLinkPrismatic::RobotLinkPrismatic(double a, double alpha, double theta, double robot2dh_offset=0.0, bool robot2dh_flip=false, double Joint_Hard_limit_lower=-INFINITY, double Joint_Hard_limit_higher=INFINITY, double hard_velocity_limit=INFINITY, std::string name=&quot;joint_no_name&quot;)']]],
  ['robotlinkprismatic_2ecpp_102',['RobotLinkPrismatic.cpp',['../RobotLinkPrismatic_8cpp.html',1,'']]],
  ['robotlinkprismatic_2eh_103',['RobotLinkPrismatic.h',['../RobotLinkPrismatic_8h.html',1,'']]],
  ['robotlinkprismaticptr_104',['RobotLinkPrismaticPtr',['../namespacesun.html#af5459bc5ac306336cf9667b1a3854989',1,'sun']]],
  ['robotlinkptr_105',['RobotLinkPtr',['../namespacesun.html#a5dc6b30f49016ea9b26a2cc819279f29',1,'sun']]],
  ['robotlinkrevolute_106',['RobotLinkRevolute',['../classsun_1_1RobotLinkRevolute.html',1,'sun::RobotLinkRevolute'],['../classsun_1_1RobotLinkRevolute.html#ad520f94595d37189dba505e82bea5887',1,'sun::RobotLinkRevolute::RobotLinkRevolute(double a, double alpha, double d, double robot2dh_offset, bool robot2dh_flip, double Joint_Hard_limit_lower, double Joint_Hard_limit_higher, double Joint_Soft_limit_lower, double Joint_Soft_limit_higher, double hard_velocity_limit, double soft_velocity_limit, std::string name=&quot;joint_no_name&quot;)'],['../classsun_1_1RobotLinkRevolute.html#aed8b0b960ea9f1d485bbefb10f783a06',1,'sun::RobotLinkRevolute::RobotLinkRevolute(double a, double alpha, double d, double robot2dh_offset=0.0, bool robot2dh_flip=false, double Joint_Hard_limit_lower=-INFINITY, double Joint_Hard_limit_higher=INFINITY, double hard_velocity_limit=INFINITY, std::string name=&quot;joint_no_name&quot;)']]],
  ['robotlinkrevolute_2ecpp_107',['RobotLinkRevolute.cpp',['../RobotLinkRevolute_8cpp.html',1,'']]],
  ['robotlinkrevolute_2eh_108',['RobotLinkRevolute.h',['../RobotLinkRevolute_8h.html',1,'']]],
  ['robotlinkrevoluteptr_109',['RobotLinkRevolutePtr',['../namespacesun.html#a576ff3dd0f09a03d923c099a93461fe5',1,'sun']]],
  ['robotptr_110',['RobotPtr',['../namespacesun.html#a0a3ae236946becebe0b86c9d8d37aea1',1,'sun']]]
];
