var searchData=
[
  ['change_5fjacob_5fframe',['change_jacob_frame',['../classsun_1_1Robot.html#af51bf1115eb15565636647b4c45058fe',1,'sun::Robot']]],
  ['checkhardjointlimits',['checkHardJointLimits',['../classsun_1_1Robot.html#acaec99786041b7b0f31f43cd99c23ba5',1,'sun::Robot']]],
  ['checkhardvelocitylimits',['checkHardVelocityLimits',['../classsun_1_1Robot.html#a34064bdb5d04c879b7c5cc1bd689328d',1,'sun::Robot']]],
  ['checkhomog',['checkHomog',['../classsun_1_1Robot.html#af4cb79015155fe6427e3df8b917b47dc',1,'sun::Robot']]],
  ['checklowerhigher',['checkLowerHigher',['../classsun_1_1RobotLink.html#a81180a2ae5c7043e7b3c8de636c1c01f',1,'sun::RobotLink']]],
  ['checksoftjointlimits',['checkSoftJointLimits',['../classsun_1_1Robot.html#a2443bb2a52f8d5ac95c24e1ad17278cf',1,'sun::Robot']]],
  ['checksoftvelocitylimits',['checkSoftVelocityLimits',['../classsun_1_1Robot.html#af8f3769ac8bd08ad79b7d0043f91e241',1,'sun::Robot']]],
  ['clik',['clik',['../classsun_1_1Robot.html#afb9982480b3298cabeb8faf1bebb27fe',1,'sun::Robot::clik(const TooN::Vector&lt;&gt; &amp;qDH_k, const TooN::Vector&lt; 6 &gt; &amp;error, const TooN::Matrix&lt;&gt; &amp;jacob, const TooN::Vector&lt; 6 &gt; &amp;veld, double gain, double Ts, double gain_null_space, const TooN::Vector&lt;&gt; &amp;q0_p, TooN::Vector&lt;&gt; &amp;qpDH)'],['../classsun_1_1Robot.html#afa57ff54a03d8cc6b97c263dc0cfde89',1,'sun::Robot::clik(const TooN::Vector&lt;&gt; &amp;qDH_k, const TooN::Vector&lt; 3 &gt; &amp;pd, const UnitQuaternion &amp;Qd, const UnitQuaternion &amp;oldQ, const TooN::Vector&lt; 3 &gt; &amp;dpd, const TooN::Vector&lt; 3 &gt; &amp;omegad, const TooN::Vector&lt; 6, int &gt; &amp;mask, double gain, double Ts, double gain_null_space, const TooN::Vector&lt;&gt; &amp;q0_p, TooN::Vector&lt;&gt; &amp;qpDH, TooN::Vector&lt; 6 &gt; &amp;error, UnitQuaternion &amp;actualQ)'],['../classsun_1_1Robot.html#aa29bc60b68b2b9476e2e5076021e5f16',1,'sun::Robot::clik(const TooN::Vector&lt;&gt; &amp;qDH_k, const TooN::Vector&lt; 3 &gt; &amp;pd, const UnitQuaternion &amp;Qd, const UnitQuaternion &amp;oldQ, const TooN::Vector&lt; 3 &gt; &amp;dpd, const TooN::Vector&lt; 3 &gt; &amp;omegad, double gain, double Ts, double gain_null_space, const TooN::Vector&lt;&gt; &amp;q0_p, TooN::Vector&lt;&gt; &amp;qpDH, TooN::Vector&lt; 6 &gt; &amp;error, UnitQuaternion &amp;actualQ)'],['../classsun_1_1Robot.html#ae5476e6f3487c730611b22f762a617c4',1,'sun::Robot::clik(const TooN::Vector&lt;&gt; &amp;qDH_k, const TooN::Vector&lt; 3 &gt; &amp;pd, const UnitQuaternion &amp;Qd, const UnitQuaternion &amp;oldQ, const TooN::Vector&lt; 3 &gt; &amp;dpd, const TooN::Vector&lt; 3 &gt; &amp;omegad, const TooN::Vector&lt; 6, int &gt; &amp;mask, double gain, double Ts, double gain_null_space, const TooN::Vector&lt;&gt; &amp;desired_configuration, const TooN::Vector&lt;&gt; &amp;desired_configuration_joint_weights, TooN::Vector&lt;&gt; &amp;qpDH, TooN::Vector&lt; 6 &gt; &amp;error, UnitQuaternion &amp;actualQ)'],['../classsun_1_1Robot.html#aa50a9e3a854d06e37f42ee5cd65503ca',1,'sun::Robot::clik(const TooN::Vector&lt;&gt; &amp;qDH_k, const TooN::Vector&lt; 3 &gt; &amp;pd, const UnitQuaternion &amp;Qd, const UnitQuaternion &amp;oldQ, const TooN::Vector&lt; 3 &gt; &amp;dpd, const TooN::Vector&lt; 3 &gt; &amp;omegad, double gain, double Ts, double gain_null_space, const TooN::Vector&lt;&gt; &amp;desired_configuration, const TooN::Vector&lt;&gt; &amp;desired_configuration_joint_weights, TooN::Vector&lt;&gt; &amp;qpDH, TooN::Vector&lt; 6 &gt; &amp;error, UnitQuaternion &amp;actualQ)']]],
  ['clone',['clone',['../classsun_1_1Robot.html#a9c2fe156be6fa0f573e6a22faeead4b6',1,'sun::Robot::clone()'],['../classsun_1_1RobotLink.html#a7f6e5f2d301c547d60d149ed673e8bd3',1,'sun::RobotLink::clone()'],['../classsun_1_1RobotLinkPrismatic.html#a6080078cbc391eaf3decae7b31e0c116',1,'sun::RobotLinkPrismatic::clone()'],['../classsun_1_1RobotLinkRevolute.html#a893342aae373b7ac852b4c7e4559a267',1,'sun::RobotLinkRevolute::clone()']]]
];
